---
- name: Install homedir
  git:
    repo: "git@github.com:{{git_username}}/homedir.git"
    dest: "{{homedir}}/{{username}}/{{personal_dir}}/homedir"
    version: main
    accept_hostkey: yes

- name: Symlink dot files
  file:
    src: "{{homedir}}/{{username}}/{{personal_dir}}/homedir/{{item}}"
    dest: "{{homedir}}/{{username}}/{{item}}"
    owner: "{{username}}"
    group: "{{usergroup}}"
    state: link
  with_items:
    - .vim
    - .vimrc
